M48
; DRILL file {KiCad 9.0.1} date 2025-10-01T12:05:25-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-01T12:05:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X236.5Y-65.75
T2
X229.375Y-90.96
X229.375Y-102.39
T3
X77.0Y-54.75
X77.0Y-152.0
X231.5Y-150.5
X232.0Y-54.75
M30
